/*
 * @HenryHuang
 * passwordCreator.java
 * April 17,2018
 * This program is uses to create passwords from the information that has been entered
 * by the users, the users can choose the length of password they want, and at the 
 * same time, they can also choose the security of the password.
 */

/**
 *
 * @author shhua8751
 */
public class FormPasswordCreator extends javax.swing.JFrame {

    /**
     * Creates new form FormPasswordCreator
     */
    public FormPasswordCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        creatorLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        interestLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        interestInput = new javax.swing.JTextField();
        yearInput = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        ieLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eightButton = new javax.swing.JRadioButton();
        sixteenButton = new javax.swing.JRadioButton();
        tenButton = new javax.swing.JRadioButton();
        twelveButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        esayButton = new javax.swing.JRadioButton();
        mediumButton = new javax.swing.JRadioButton();
        hardButton = new javax.swing.JRadioButton();
        userNameLabel = new javax.swing.JLabel();
        userNameInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateInput = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        creatorLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        creatorLabel.setForeground(new java.awt.Color(255, 0, 51));
        creatorLabel.setText("Password Creator");

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameLabel.setText("Enter Your Name: ");

        interestLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        interestLabel.setText("Enter Your Interest: ");

        yearLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearLabel.setText("Enter Your Birth Year : ");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        outputLabel.setForeground(new java.awt.Color(255, 51, 51));

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateLabel.setText("Enter Your Birth Date:");

        ieLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        ieLabel.setText("( ie.Programming)");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Length of the password: ");

        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        sixteenButton.setText("16");

        tenButton.setText("10");

        twelveButton.setText("12");
        twelveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelveButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Password Sercurity: ");

        esayButton.setText("Easy");
        esayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esayButtonActionPerformed(evt);
            }
        });

        mediumButton.setText("Medium");
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });

        hardButton.setText("Hard");
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLabel.setText("Enter Your User Name: ");

        userNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("(First or Last)");

        dateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(ieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(interestLabel)
                            .addComponent(NameLabel)
                            .addComponent(userNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameInput)
                            .addComponent(nameInput)
                            .addComponent(interestInput)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearInput)
                            .addComponent(dateInput)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mediumButton)
                            .addComponent(hardButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tenButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(twelveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sixteenButton))
                            .addComponent(esayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creatorLabel)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creatorLabel)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestLabel)
                    .addComponent(interestInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ieLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eightButton)
                    .addComponent(tenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twelveButton)
                    .addComponent(sixteenButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(esayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mediumButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hardButton)
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addGap(18, 18, 18)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        //Listing all the strings would be uses in the program.
        String name;
        String interest;
        String userName;
        String year;
        String date;
        
       
        name = nameInput.getText();
        interest = interestInput.getText();
        userName = userNameInput.getText();
        year = yearInput.getText();
        date = dateInput.getText();
        //To get the information that the user has typed in the textfield.
        
        if (eightButton.isSelected())
        {
            //This code wiill be active when the user choose radio button with "8", same with the rest.
            if (esayButton.isSelected())
            {
                //This code will be active when the user click on the "easy" radio button, same with the rest.
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + date  + year);
            }
            else if(mediumButton.isSelected())
            {
                //This code will be active whent the user choose "medium" radio button, same with the rest.
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(0)+name.charAt(1)  +
                        interest.charAt(0) +interest.charAt(1) + date);
            }
            else if (hardButton.isSelected())
            {
                //This code will be active whent the user choose "hard" radio button.
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(0)+name.charAt(1)  +
                        year + interest.charAt(0) + interest.charAt(1) );        

            }
        }
        
        else if(tenButton.isSelected())
        {
           if (esayButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(0)+name.charAt(1) + date + year );
            }
            else if(mediumButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(3)+
                        date +  interest.charAt(4) + year);
            }
            else if (hardButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(2)+interest.charAt(0)+name.charAt(1)  +
                        year + interest.charAt(2) + interest.charAt(0)+name.charAt(1) );        

            } 
        }
        
        else if (twelveButton.isSelected())
        {
            if (esayButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(0)+name.charAt(1)+
                         +  interest.charAt(2)+ interest.charAt(1) + date + year );
            }
            else if(mediumButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(2)+ interest.charAt(0)+
                        date +  interest.charAt(1)+ name.charAt(0) + year);
            }
            else if (hardButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(2)+ "+" +interest.charAt(2)+name.charAt(1)+ "+" +
                        year + interest.charAt(1) + interest.charAt(0)+ name.charAt(0) );      
            }
        }
            
        else if (sixteenButton.isSelected())
        {
            if (esayButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(0)+name.charAt(2)+
                        date + interest.charAt(1)+ name.charAt(1)+ interest.charAt(1)+
                        interest.charAt(2) + name.charAt(2)+ interest.charAt(0)+ year );
            }
            else if(mediumButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(2)+ "+" + interest.charAt(0)+
                        name.charAt(2)+ year +  interest.charAt(1)+ "+" + name.charAt(0) 
                        + name.charAt(1) + date);
            }
            else if (hardButton.isSelected())
            {
                outputLabel.setText("Your username is :" + userName + "   " 
                        + "Your Password is :" + name.charAt(2)+ "+" +interest.charAt(2)+ "+" + name.charAt(0)+ "+" 
                        + date + "+"  + interest.charAt(0) + "+" + interest.charAt(1)+ "+" + name.charAt(1) );
            }
            //All the conditions above will only be active when the two conditons are both true or choose.
            //Different contions will have different password created.
            
        }
          
    }//GEN-LAST:event_createButtonActionPerformed

    private void twelveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twelveButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed

    }//GEN-LAST:event_eightButtonActionPerformed

    private void esayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esayButtonActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hardButtonActionPerformed

    private void dateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateInputActionPerformed

    private void userNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPasswordCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPasswordCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPasswordCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPasswordCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPasswordCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JTextField dateInput;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton eightButton;
    private javax.swing.JRadioButton esayButton;
    private javax.swing.JRadioButton hardButton;
    private javax.swing.JLabel ieLabel;
    private javax.swing.JTextField interestInput;
    private javax.swing.JLabel interestLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JRadioButton sixteenButton;
    private javax.swing.JRadioButton tenButton;
    private javax.swing.JRadioButton twelveButton;
    private javax.swing.JTextField userNameInput;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField yearInput;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
